version: '3.8'
services:
    app:
        user: '1100'
        volumes:
            - /wordpress/data/app:/var/www/html

    nginx:
        environment:
            DOMAIN_NAME: candidates.frcaction.org
        deploy:
            labels:
                traefik.http.routers.candidatetraining.rule: Host(`candidates.frcaction.org`)
            placement:
                constraints:
                    - node.role == worker
        networks:
            - traefik
            - default
        volumes:
            - /wordpress/data/app:/var/www/html

    mysql:
        volumes:
            - /wordpress/data/mysql:/var/lib/mysql

networks:
    traefik:
        external: true